export const Pages = [
    {
        id: 0,
        title: 'Landing Page',
        url: '/src/images/landingpage.jpg',
        imgAlt: 'preview',
        description: '',
        link: '/',
        buttonText: 'View',
    },
    {
        id: 1,
        title: 'Projects',
        url: '/src/images/projectpage.jpg',
        imgAlt: 'preview',
        description: 'View the projects we have been working on!',
        link: '/Projects',
        buttonText: 'View',
    },
    {
        id: 2,
        title: 'About Us',
        url: '/src/images/aboutus.jpg',
        imgAlt: 'preview',
        description: 'Learn about our facility!',
        link: '/Aboutus',
        buttonText: 'View',
    },
    {
        id: 3,
        title: 'Our Team',
        url: '/src/images/General/Shovic_Squad_April_Fools.jpg',
        imgAlt: 'preview',
        description: 'Come learn about the people that make up the team!',
        link: '/Team',
        buttonText: 'View',
    },
    {
        id: 4,
        title: 'Publications',
        url: 'src/images/EvergreenPhotos/evergreen-robot.jpg',
        imgAlt: 'preview',
        description: 'Learn about our most recent publications!',
        link: '/Publications',
        buttonText: 'View',
    },
    {
        id: 5,
        title: 'Contact Us',
        url: 'src/images/AutomationPhotos/Automation-board-on-conveyor.jpg',
        imgAlt: 'preview',
        description: 'If you have any questions feel free to contact us!',
        link: '/Contactus',
        buttonText: 'View',
    },
]