export const Papers = [
    {
        id: 0,
        name: 'Data Gator',
        description: '“A Provisionless Network Solution for Collecting Data from Wired and Wireless Sensors”, 16th International Conference on Precision Agriculture.',
        authors: 'Garrett Wells, Mary Everett, John Shovic',
        location: 'July 2024, Manhattan, Kansas (Paper and Oral Presentation)',
        link: 'link',
    },
    {
        id: 1,
        name: 'Neural Network',
        description: '“Explainable Neural Network Alternatives for AI Predictions: Genetic Algorithm Quantitative Association Rule Mining”, 16th International Conference on Precision Agriculture.',
        authors: 'Mary Everett',
        location: 'July 2024, Manhattan, Kansas (Paper and Oral Presentation)',
        link: 'link',
    },
    {
        id: 2,
        name: 'Flexible Software Architecture',
        description: '“A Flexible Software Architecture for General Precision Agriculture Decision Support Systems”, 16th International Conference on Precision Agriculture.',
        authors: 'Walter Neils, Dustin Mommen',
        location: 'July 2024, Manhattan, Kansas (Paper and Oral Presentation)',
        link: 'link',
    },
    {
        id: 3,
        name: 'Agriculture Sensor',
        description: '“Recovery Mechanism for Real-time Precision Agriculture Sensor Networks: a Case Study”, 16th International Conference on Precision Agriculture.',
        authors: 'Lacey Hunt, Mary Everett, John Shovic',
        location: 'July 2024, Manhattan, Kansas (Paper and Poster Presentation)',
        link: 'link',
    },
    {
        id: 4,
        name: 'Dimensionality Reduction',
        description: '“Dimensionality Reduction and Similarity Metrics for Predicting Crop Yields in Sparse Data Microclimates”, 16th International Conference on Precision Agriculture.',
        authors: 'Leif Huender, Mary Everett',
        location: 'July 2024, Manhattan, Kansas (Paper and Poster Presentation)',
        link: 'link',
    },
]