export const People = [
    {
        id: 0,
        firstName: 'John',
        lastName: 'Shovic',
        title: 'Dr.',
        position: 'Director',
        photo: 'src/images/ProfilePhotos/john-shovic.jpg',
        imgAlt: 'John Shovic',
        decription: 'Dr. John Shovic is the Director of the Center for Intelligent Industrial Robotics and Research Faculty in the College of Engineering at the University of Idaho. He is located in the Coeur d’Alene computer science department on the NIC campus. Dr. Shovic spent 25 years in industry as the CEO and founder of a number of different research oriented startup companies before joining the University of Idaho. His research interests include automation, robotics, and AI for manufacturing industries.',
        email: 'jshovic@uidaho.edu',
    },
    {
        id: 1,
        firstName: 'Robert',
        lastName: 'Rinker',
        title: 'Dr.',
        position: 'Associate Professor / Chair of Computer Science',
        photo: 'src/images/ProfilePhotos/robert-rinker.jpg',
        imgAlt: 'personal photo',
        decription: 'Dr. Robert Rinker is an associate professor of Computer Science, and associate chair for Computer Science in Coeur d’Alene, Idaho. He has worked extensively with undergraduate students in multiple disciplines (STEM and non-STEM) through work with embedded systems, including teaching soldering workshops for the UI Lionel Hampton School of Music for a electronic marching band glasses project. Dr. Rinker’s projects focus on embedded systems and advanced computer architecture. He is located on the Coeur d’Alene campus.',
        email: 'rinker@uidaho.edu',
    },
    {
        id: 2,
        firstName: 'Tammy',
        lastName: 'St. John-Tesky',
        title: '',
        position: 'Administrative Coordinator',
        photo: 'src/images/ProfilePhotos/st-john-tesky.jpg',
        imgAlt: 'personal photo',
        decription: 'Tammy St John-Tesky is the Administrative Coordinator for the University of Idaho Computer Science Department in Coeur d’Alene and is also serving as the Administrative Coordinator for the center. Her focus areas include staff and student support, outreach, as well as assisting with all other needs of the center. She also enjoys working with and supporting all of the fantastic students in the center’s undergraduate research cohort at University of Idaho Coeur d’Alene and North Idaho College. ',
        email: 'tammy@uidaho.edu',
    },
    {
        id: 3,
        firstName: 'Mary "Marz"',
        lastName: ' Everett',
        title: 'Dr.',
        position: 'Associate Director',
        photo: 'src/images/ProfilePhotos/M_Everett.jpg',
        imgAlt: 'personal photo',
        decription: 'Marz Everett is a postdoctoral fellow at the University of Idaho and serving as the associate director for the center. Her research focus areas include precision agriculture, wireless sensing network systems, manufacturing, and artificial intelligence and data science analysis in the above areas. She also enjoys mentoring many of the fantastic students in the Center’s undergraduate research cohort at University of Idaho Coeur d’Alene and North Idaho College. ',
        email: 'meverett@uidaho.edu',
    },
]