export const People = [
    {
        id: 3,
        firstName: 'John',
        lastName: 'Shovic',
        title: 'Dr.',
        position: 'Director',
        photo: 'src/images/ProfilePhotos/john-shovic.jpg',
        imgAlt: 'John Shovic',
        decription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        email: 'jshovic@uidaho.edu',
    },
    {
        id: 4,
        firstName: 'Robert',
        lastName: 'Rinker',
        title: 'Dr.',
        position: 'Director',
        photo: 'src/images/ProfilePhotos/robert-rinker.jpg',
        imgAlt: 'personal photo',
        decription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        email: 'rinker@uidaho.edu',
    },
    {
        id: 5,
        firstName: 'Tammy',
        lastName: 'St. John-Tesky',
        title: '',
        position: 'Administrative Coordinator',
        photo: 'src/images/ProfilePhotos/st-john-tesky.jpg',
        imgAlt: 'personal photo',
        decription: 'Tammy St John-Tesky is the Administrative Coordinator for the University of Idaho Computer Science Department in Coeur d’Alene and is also serving as the Administrative Coordinator for the center. Her focus areas include staff and student support, outreach, as well as assisting with all other needs of the center. She also enjoys working with and supporting all of the fantastic students in the center’s undergraduate research cohort at University of Idaho Coeur d’Alene and North Idaho College. ',
        email: 'tammy@uidaho.edu',
    },
    {
        id: 6,
        firstName: 'Mary "Marz"',
        lastName: ' Everett',
        title: 'Dr.',
        position: 'Associate Director',
        photo: 'src/images/ProfilePhotos/M_Everett.jpg',
        imgAlt: 'personal photo',
        decription: 'Marz Everett is a postdoctoral fellow at the University of Idaho and serving as the associate director for the center. Her research focus areas include precision agriculture, wireless sensing network systems, manufacturing, and artificial intelligence and data science analysis in the above areas. She also enjoys mentoring many of the fantastic students in the Center’s undergraduate research cohort at University of Idaho Coeur d’Alene and North Idaho College. ',
        email: 'meverett@uidaho.edu',
    },
]