export const Projects = [
    {
        id: 0,
        title: 'SCARECRO',
        altImage: 'SCARECRO',
        url: '/src/images/dashboard.png',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/Scarecro',
    },
    {
        id: 1,
        title: 'Project Evergreen',
        altImage: 'Project Evergreen',
        url: '/src/images/minifactory.webp',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/Evergreen',
    },
    {
        id: 2,
        title: 'Aquifer Pumped Hydro',
        altImage: 'Aquifer Pumped Hydro',
        url: '/src/images/aquiferpump.jpg',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/Aquifer',
    },
    {
        id: 3,
        title: 'Manufacturing AI Data',
        altImage: 'Manufacturing AI Data',
        url: '/src/images/AI.webp',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/AiData',
    },
    {
        id: 4,
        title: 'Valley Fever',
        altImage: 'Robotics',
        url: '/src/images/cobot.jpg',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/ValleyFever',
    },
    {
        id: 5,
        title: 'FarmBot',
        altImage: 'FarmBot',
        url: 'src/images/farmbot.webp',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/FarmBot',
    },
    {
        id: 6,
        title: 'Automation',
        altImage: 'Automation',
        url: 'src/images/AI.webp',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/Automation',
    },
]