export const Projects = [
    {
        id: 0,
        title: 'SCARECRO',
        altImage: 'SCARECRO',
        url: 'src/images/ScarecroPhotos/SOAC_Marz_Lacey.jpg',
        description: 'The SCARECRO System (an only mildly-forced acronym that stands for Sensor Collection and Remote Environment Care Reasoning Operation)...',
        buttonText: 'Learn More',
        link: '/Scarecro',
    },
    {
        id: 1,
        title: 'Project Evergreen',
        altImage: 'Project Evergreen',
        url: 'src/images/EvergreenPhotos/group-photo-evergreen.jpg',
        description: 'Funded by the United States Forest Service and the USDA, Project Evergreen is developing an autonomous weeding robot for National Forest tree seedling nurseries...',
        buttonText: 'Learn More',
        link: '/Evergreen',
    },
    {
        id: 2,
        title: 'Aquifer Pumped Hydro',
        altImage: 'Aquifer Pumped Hydro',
        url: '',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/Aquifer',
    },
    {
        id: 3,
        title: 'Manufacturing AI Data',
        altImage: 'Manufacturing AI Data',
        url: '',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/AiData',
    },
    {
        id: 4,
        title: 'Valley Fever',
        altImage: 'Robotics',
        url: '',
        description: 'Mary has the description for all of the imformation about the SCARECRO project as well as the picture that go with it',
        buttonText: 'Learn More',
        link: '/ValleyFever',
    },
    {
        id: 5,
        title: 'FarmBot',
        altImage: 'FarmBot',
        url: 'src/images/FarmBotPhotos/farmbot-plant-view.jpg',
        description: 'These devices, which automatically plant and water, are being used in conjunction with PLCs and a custom lighting gantry to extend their operation indoors...',
        buttonText: 'Learn More',
        link: '/FarmBot',
    },
    {
        id: 6,
        title: 'Automation',
        altImage: 'Automation',
        url: 'src/images/AutomationPhotos/Automation-in-action.jpg',
        description: 'Students work with different robots and robotics systems including ROS (Robot Operating System), Fanuc CRX-10 robots, a Fanuc P50ib robot, Create3 Robots...',
        buttonText: 'Learn More',
        link: '/Automation',
    },
]